# Generated by Django 3.1.3 on 2021-05-24 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20210524_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='paind',
            new_name='paid',
        ),
    ]
