# Generated by Django 3.1.3 on 2021-06-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=128)),
                ('slug', models.TextField(max_length=28)),
                ('website', models.TextField(max_length=128)),
                ('photo', models.TextField(max_length=128)),
                ('description', models.TextField(max_length=512)),
            ],
        ),
    ]
