# Generated by Django 3.1.3 on 2021-06-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210606_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='kind',
            field=models.TextField(max_length=1, verbose_name='nome'),
        ),
    ]
