# Generated by Django 3.1.3 on 2021-06-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210606_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='kind',
            field=models.TextField(choices=[('E', 'Email'), ('P', 'Telefone')], max_length=1, verbose_name='nome'),
        ),
    ]
